import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  content: {
    flex: 1,
    padding: 12,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 16,
    elevation: 2,
    padding: 6,
    width: '100%',
  },
  actionButton: {
    backgroundColor: COLORS.primary,
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    width: '100%',
  },
  actionButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modelsList: {
    padding: 8,
  },
  modelListCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 10,
    elevation: 2,
    padding: 15,
  },
  header: {
    padding: 20,
    backgroundColor: '#fff',
  },
  modelCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
    elevation: 2,
    width: '100%',
    marginHorizontal: 0,
  },
  modelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  modelHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modelTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modelFamilia: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: 'bold',
    backgroundColor: COLORS.primary + '15',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  modelTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  modelInfo: {
    width: '100%',
    marginTop: 5,
    paddingTop: 5,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  infoColumn: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  infoLabel: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 4,
    opacity: 0.8,
  },
  infoValue: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 8,
    fontWeight: '500',
    textAlign: 'center',
  },
  resistenciaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ohmsLabel: {
    fontSize: 16,
    color: COLORS.text,
    marginRight: 4,
  },
  resistenciaValue: {
    fontSize: 16,
    color: COLORS.text,
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 12,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 20,
    elevation: 5,
    width: '100%',
    maxHeight: '90%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    padding: 10,
    fontSize: 14,
    height: 50,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    marginBottom: 15,
    overflow: 'hidden',
    height: 50,
  },
  picker: {
    height: 50,
  },
  inputRow: {
    flexDirection: 'column',
    marginBottom: 15,
  },
  inputColumn: {
    width: '100%',
    marginBottom: 10,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 10,
    gap: 12,
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: COLORS.danger,
  },
  submitButton: {
    backgroundColor: COLORS.primary,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  closeButton: {
    padding: 5,
  },
  closeButtonText: {
    fontSize: 24,
    color: COLORS.text,
    fontWeight: 'bold',
  },
  modelName: {
    fontSize: 16,
    color: COLORS.text,
    fontWeight: '500',
  },
  modelDetails: {
    flexDirection: 'row',
    padding: 10,
  },
  wireColumn: {
    flex: 1,
  },
  wireLabel: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 4,
  },
  wireValue: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  ohmsContainer: {
    marginTop: 4,
  },
  ohmsValue: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '500',
  },
  modelActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
  },
  actionIconButton: {
    padding: 8,
  },
  removeButton: {
    padding: 4,
  },
  iconButton: {
    alignItems: 'center',
    padding: 15,
    borderRadius: 8,
  },
  iconButtonText: {
    marginTop: 8,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '500',
  },
  fioInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  fioInput: {
    flex: 0.4,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    padding: 10,
    fontSize: 14,
    height: 50,
  },
  tipoFioContainer: {
    flex: 0.6,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    height: 50,
    overflow: 'hidden',
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
  },
  tipoFioPicker: {
    height: 50,
    width: '100%',
    color: COLORS.text,
    fontSize: 14,
  },
  infoHeader: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 4,
    fontWeight: 'bold',
  },
  listContent: {
    padding: 20,
    paddingBottom: 40,
  },
  modelContent: {
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 12,
    width: '100%',
  },
  fioContainer: {
    marginBottom: 8,
  },
  fioTitle: {
    fontSize: 12,
    color: COLORS.text,
    marginBottom: 4,
    opacity: 0.7,
  },
  fioInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fioValue: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.text,
  },
  divider: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 8,
  },
  menuButton: {
    flex: 1,
    paddingVertical: 8,
  },
  menuButtonContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButtonText: {
    marginTop: 4,
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  buttonDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#e0e0e0',
    marginHorizontal: 6,
  },
  fioDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  fioTipo: {
    fontSize: 12,
    color: COLORS.primary,
    backgroundColor: COLORS.primary + '15',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontWeight: '500',
  },
  fabContainer: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    alignItems: 'flex-end',
  },
  fabMain: {
    backgroundColor: COLORS.primary,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  fabMainExpanded: {
    backgroundColor: COLORS.danger,
  },
  fabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  fabItemPrimary: {
    backgroundColor: COLORS.primary,
  },
  fabItemSecondary: {
    backgroundColor: COLORS.text,
  },
  fabItemText: {
    color: '#FFF',
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
  },
}); 




